### PR TITLE
muezzinoglu

### PR DESCRIPTION
**Pull request by mustafamuezzinoglu**

### CODE REVIEW

**Review by mehmetakkaya09 — COMMENTED** [review]
done

**Review by Makaraoglan — APPROVED** [review]

**Comment by Apakyol** [comment]
reviewed

**Review by omeryldz1 — APPROVED** [review]

**Review by mehmetakkaya09 — APPROVED** [review]
done

**Comment by Apakyol** [comment]
reviewed

**Review by Makaraoglan — APPROVED** [review]

**Review by MustafaAtik76 — APPROVED** [review]

**Review by Apakyol — COMMENTED** [review]
reviewed

**Comment by Apakyol** [comment]
reviewed

**Review by Apakyol — COMMENTED** [review]
ok

**Comment by Apakyol** [comment]
reviewed

**Comment by Apakyol** [comment]
reviewed

**Review by Apakyol — COMMENTED** [review]
reviewed

**Comment by Apakyol** [comment]
reviewed...

**Review by Apakyol — COMMENTED** [review]
reviewed.

**Review by Apakyol — COMMENTED** [review]
reviewed. ok

**Comment by Apakyol** [comment]
ok

**Comment by Apakyol** [comment]
ok

**Comment by Apakyol** [comment]
reviewed.

**Pull request merged**
